{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d0d3f96d-1207-4838-b1d3-489481292dc0",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import ttk\n",
    "\n",
    "# Function to validate that the user enters only signed integers\n",
    "def validate_integer(value_if_allowed):\n",
    "    if value_if_allowed in ('', '-', '+'):\n",
    "        return True\n",
    "    try:\n",
    "        int(value_if_allowed)\n",
    "        return True\n",
    "    except ValueError:\n",
    "        return False\n",
    "\n",
    "# Function to perform the temperature conversion\n",
    "def convert_temperature():\n",
    "    try:\n",
    "        value = int(entry_value.get())\n",
    "        unit = unit_choice.get()\n",
    "\n",
    "        if unit == \"Celsius (°C)\":\n",
    "            f = (value * 9/5) + 32\n",
    "            k = value + 273.15\n",
    "            result.set(f\"{value}°C = {f:.1f}°F\\n→ {k:.2f} K\")\n",
    "\n",
    "        elif unit == \"Fahrenheit (°F)\":\n",
    "            c = (value - 32) * 5/9\n",
    "            k = c + 273.15\n",
    "            result.set(f\"{value}°F = {c:.1f}°C\\n→ {k:.2f} K\")\n",
    "\n",
    "        elif unit == \"Kelvin (K)\":\n",
    "            c = value - 273.15\n",
    "            f = (c * 9/5) + 32\n",
    "            result.set(f\"{value} K = {c:.1f}°C\\n→ {f:.2f}°F\")\n",
    "\n",
    "    except ValueError:\n",
    "        result.set(\"⚠️ Please enter a valid number.\")\n",
    "\n",
    "# Window setup\n",
    "root = tk.Tk()\n",
    "root.title(\"🔥 Temperature Converter 🌡️\")\n",
    "root.geometry(\"460x320\")\n",
    "root.resizable(False, False)\n",
    "\n",
    "# Gradient background simulation\n",
    "canvas = tk.Canvas(root, width=460, height=320)\n",
    "canvas.pack(fill=\"both\", expand=True)\n",
    "\n",
    "for i in range(0, 320):\n",
    "    r = int(255 * (i / 320))\n",
    "    b = int(255 * (1 - i / 320))\n",
    "    color = f'#ff{r:02x}{b:02x}'\n",
    "    canvas.create_line(0, i, 460, i, fill=color)\n",
    "\n",
    "# Main frame\n",
    "frame = tk.Frame(root, bg=\"#ffffff\", bd=2, relief=\"ridge\", padx=20, pady=20)\n",
    "frame.place(relx=0.5, rely=0.5, anchor=\"center\")\n",
    "\n",
    "# Input field with validation\n",
    "vcmd = root.register(validate_integer)\n",
    "\n",
    "tk.Label(frame, text=\"Enter Temperature\", font=(\"Segoe UI\", 11), bg=\"#ffffff\").grid(row=0, column=0, pady=(5, 0))\n",
    "entry_value = tk.Entry(\n",
    "    frame,\n",
    "    font=(\"Segoe UI\", 12),\n",
    "    justify=\"center\",\n",
    "    width=20,\n",
    "    validate=\"key\",\n",
    "    validatecommand=(vcmd, \"%P\"),\n",
    "    relief=\"groove\"\n",
    ")\n",
    "entry_value.grid(row=1, column=0, pady=5)\n",
    "\n",
    "# Unit selector\n",
    "tk.Label(frame, text=\"Select Unit\", font=(\"Segoe UI\", 11), bg=\"#ffffff\").grid(row=2, column=0, pady=(10, 0))\n",
    "unit_choice = ttk.Combobox(frame, values=[\"Celsius (°C)\", \"Fahrenheit (°F)\", \"Kelvin (K)\"], font=(\"Segoe UI\", 10))\n",
    "unit_choice.set(\"Celsius (°C)\")\n",
    "unit_choice.grid(row=3, column=0, pady=5)\n",
    "\n",
    "# Convert button with hover effect\n",
    "def on_hover(event):\n",
    "    convert_btn.config(bg=\"#ffebee\", fg=\"#b71c1c\")\n",
    "\n",
    "def on_leave(event):\n",
    "    convert_btn.config(bg=\"#ffffff\", fg=\"#d84315\")\n",
    "\n",
    "convert_btn = tk.Button(\n",
    "    frame,\n",
    "    text=\"🔥 Convert 🔁\",\n",
    "    command=convert_temperature,\n",
    "    font=(\"Segoe UI Semibold\", 12),\n",
    "    bg=\"#ffffff\",\n",
    "    fg=\"#d84315\",\n",
    "    activebackground=\"#ffe0b2\",\n",
    "    activeforeground=\"#bf360c\",\n",
    "    relief=\"solid\",\n",
    "    bd=2,\n",
    "    padx=14,\n",
    "    pady=8,\n",
    "    cursor=\"hand2\",\n",
    "    highlightbackground=\"#ffa726\",\n",
    "    highlightcolor=\"#ffa726\",\n",
    "    highlightthickness=2\n",
    ")\n",
    "convert_btn.grid(row=4, column=0, pady=15)\n",
    "convert_btn.bind(\"<Enter>\", on_hover)\n",
    "convert_btn.bind(\"<Leave>\", on_leave)\n",
    "\n",
    "# Result display\n",
    "result = tk.StringVar()\n",
    "tk.Label(frame, textvariable=result, font=(\"Segoe UI\", 11, \"bold\"), bg=\"#ffffff\", fg=\"#333\").grid(row=5, column=0)\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ee361d0e-d89b-4b42-8303-84cba08b9fd0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "035f48e1-625c-4d72-abab-dbd50bc1c806",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
